[package]
name = "tokio-wrap"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }

[dev-dependencies]
trybuild = "1.0.99"
tokio = { version = "1.40.0", features = ["full", "test-util"] }